base_url = "https://xorz57.pages.dev"
title = "George Fotopoulos"
description = "Software Engineer"
author = "George Fotopoulos"
compile_sass = false
minify_html = true
build_search_index = false
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true
highlight_theme = "OneHalfDark"
render_emoji = true
smart_punctuation = true

[extra]
navbar_items = [
    { title = "Home", url = "/", icon = "home-fill" },
    { title = "Posts", url = "/posts/", icon = "article-fill" }
]
social_items = [
    { title = "GitHub", url = "https://github.com/xorz57", icon = "github-fill" },
    { title = "LinkedIn", url = "https://www.linkedin.com/in/xorz57", icon = "linkedin-fill" },
    { title = "Resume", url= "https://github.com/user-attachments/files/16323564/Georgios_Fotopoulos.pdf", icon = "attachment-fill" }
]
chart = false
katex = false
mapbox_gl = false
mermaid = false

[extra.analytics]
goatcounter = "https://xorz57.goatcounter.com/count"
