base_url = "https://xorz57.pages.dev"
title = "xorz57's Blog"
description = "xorz57's Blog"
author = "xorz57"
compile_sass = true
minify_html = true
build_search_index = false
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true
smart_punctuation = true

[extra]
chart = false
mermaid = false
