base_url = "https://xorz57.pages.dev"
title = "xorz57's Blog"
description = "xorz57's Blog"
author = "xorz57"
compile_sass = false
minify_html = true
build_search_index = false
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = false

[extra]

[extra.disqus]
shortname = "xorz57"