base_url = "https://xorz57.pages.dev"
title = "xorz57"
description = "xorz57's Blog"
author = "George Fotopoulos"
compile_sass = false
minify_html = true
build_search_index = false
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true
smart_punctuation = true

[extra]
navbar_items = [
    { title = "Posts", url = "/posts", icon = "fas fa-file" }
]
social_items = [
    { title = "GitHub", url = "https://github.com/xorz57", icon = "fab fa-github" },
    { title = "LinkedIn", url = "https://www.linkedin.com/in/xorz57", icon = "fab fa-linkedin" }
]
chart = false
katex = false
mapbox_gl = false
mermaid = false

[extra.analytics]
cloudflare = "6caeba05d99b4eb8b248b937ce3a13ad"
google = "G-3RMCRXW1XD"

[extra.profile]
status = "Software Engineer"