[[project]]
name = "Morse Code Converter"
desc = "Qt Application written in C++"
tags = [ "cpp", "qt" ]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/MorseCodeConverter" },
]

[[project]]
name = "Breakout"
desc = "Game written in C++"
tags = [ "cpp", "game-programming", "sdl" ]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/Breakout" },
]

[[project]]
name = "F1 Telemetry Client"
desc = "Library written in Rust"
tags = [ "rust", "network-programming" ]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/f1-telemetry-client" },
]

[[project]]
name = "Stopwatch"
desc = "Library written in C++"
tags = [ "cpp" ]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/Stopwatch" },
]

[[project]]
name = "Logger"
desc = "Library written in C++"
tags = [ "cpp" ]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/Logger" },
]

[[project]]
name = "Pathfinder"
desc = "Application written in Python"
tags = [ "python", "algorithms" ]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/Pathfinder" },
]

[[project]]
name = "KD Tree"
desc = "Library written in Scala"
tags = [ "scala", "data-structures" ]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/KDTree" },
]
