[[project]]
name = "Morse Code Converter"
desc = "Application written in C++"
tags = ["cpp", "qt"]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/MorseCodeConverter" },
]

[[project]]
name = "Port Scanner"
desc = "Application written in C++"
tags = ["cpp", "boost"]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/PortScanner" },
]

[[project]]
name = "KD Tree"
desc = "Library written in Scala"
tags = ["scala", "data-structures"]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/KDTree" },
]
