[[project]]
name = "Morse Code Converter"
desc = "Qt Application written in C++"
tags = ["cpp", "qt"]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/MorseCodeConverter" },
]

[[project]]
name = "KD Tree"
desc = "Library written in Scala"
tags = ["scala", "data-structures"]
img = ""
links = [
  { name = "GitHub", url = "https://github.com/xorz57/KDTree" },
]
